name: dev-deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Make venv
        run : |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - name: Create .env file
        working-directory: ./
        run : |
          echo "NAVER_MAPS_CLIENT_ID=${{ secrets.NAVER_MAPS_CLIENT_ID }}" >> .env
          echo "NAVER_MAPS_CLIENT_SECRET=${{ secrets.NAVER_MAPS_CLIENT_SECRET }}" >> env
          echo "ODSAY_API_KEY=${{ secrets.ODSAY_API_KEY }}" >> env

      - name: Create Compressed file
        run: zip -r server.zip .

      - name: Upload S3
        run: aws s3 cp --region ap-southeast-1 ./server.zip s3://${{secrets.BUCKET_NAME}}/public/

      - name: Deploy CodeDeploy
        run: aws deploy create-deployment
          --application-name ${{secrets.CODEDEPLOY_APP_NAME}}
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name ${{secrets.CODEDEPLOY_DG_NAME}}
          --s3-location bucket=${{secrets.BUCKET_NAME}},bundleType=zip,key=public/server.zip